[package]
name = "jackmidiosc"
version = "0.1.0"
description = "Send MIDI data over the internet using OSC"
authors = ["piegames <piegames@darmstadt.ccc.de>"]
edition = "2018"

[dependencies]
jack = "0.6.0"
clap = "2.33.0"
rosc = "0.1.6"

log = "0.4"
simple_logger = "1.3.0"
